# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quick-admin 4.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "quick-admin"
  s.version = "4.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ryan Wong"]
  s.date = "2014-12-21"
  s.description = "\n\n    * bootstrap 3\n    * fontawesome\n    * haml\n    * datagrid\n    * responders\n    * kaminari\n\n  "
  s.email = "lazing@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "app/assets/fonts/glyphicons-halflings-regular.eot",
    "app/assets/fonts/glyphicons-halflings-regular.svg",
    "app/assets/fonts/glyphicons-halflings-regular.ttf",
    "app/assets/fonts/glyphicons-halflings-regular.woff",
    "app/assets/images/.keep",
    "app/assets/images/patterns/congruent_pentagon.png",
    "app/assets/images/patterns/header-profile-skin-1.png",
    "app/assets/images/patterns/header-profile-skin-2.png",
    "app/assets/images/patterns/header-profile-skin-3.png",
    "app/assets/images/patterns/header-profile.png",
    "app/assets/images/patterns/otis_redding.png",
    "app/assets/images/patterns/shattered.png",
    "app/assets/images/patterns/triangular.png",
    "app/assets/javascripts/quick-admin/base.js",
    "app/assets/javascripts/quick-admin/datetimepicker.coffee",
    "app/assets/stylesheets/quick-admin/base.scss",
    "app/assets/stylesheets/quick-admin/datagrid-override.css.scss",
    "app/assets/stylesheets/quick-admin/style.css.scss",
    "app/controllers/quick_admin/base_controller.rb",
    "app/helpers/quick_admin_helper.rb",
    "app/views/kaminari/_first_page.html.haml",
    "app/views/kaminari/_gap.html.haml",
    "app/views/kaminari/_last_page.html.haml",
    "app/views/kaminari/_next_page.html.haml",
    "app/views/kaminari/_page.html.haml",
    "app/views/kaminari/_paginator.html.haml",
    "app/views/kaminari/_prev_page.html.haml",
    "app/views/layouts/_menu.html.haml",
    "app/views/layouts/application.html.haml",
    "app/views/layouts/quick_admin/base.html.haml",
    "app/views/quick_admin/_action_show.html.haml",
    "app/views/quick_admin/_item.html.haml",
    "app/views/quick_admin/base/edit.html.haml",
    "app/views/quick_admin/base/index.html.haml",
    "app/views/quick_admin/base/new.html.haml",
    "app/views/quick_admin/base/show.html.haml",
    "app/views/quick_grid/_form.html.erb",
    "app/views/quick_grid/_head.html.haml",
    "app/views/quick_grid/_order_for.html.haml",
    "app/views/quick_grid/_row.html.haml",
    "app/views/quick_grid/_table.html.haml",
    "lib/assets/javascripts/.keep",
    "lib/assets/javascripts/bootstrap-datetimepicker.js",
    "lib/assets/javascripts/bootstrap-editable.js",
    "lib/assets/javascripts/bootstrap-markdown.js",
    "lib/assets/javascripts/inspinia.js",
    "lib/assets/javascripts/lang/summernote-zh-CN.js",
    "lib/assets/javascripts/locales/bootstrap-datetimepicker.zh-CN.js",
    "lib/assets/javascripts/locales/bootstrap-datetimepicker.zh-TW.js",
    "lib/assets/javascripts/markdown.js",
    "lib/assets/javascripts/plugins/chartJs/Chart.min.js",
    "lib/assets/javascripts/plugins/chosen/chosen.jquery.js",
    "lib/assets/javascripts/plugins/dataTables/dataTables.bootstrap.js",
    "lib/assets/javascripts/plugins/dataTables/jquery.dataTables.js",
    "lib/assets/javascripts/plugins/datapicker/bootstrap-datepicker.js",
    "lib/assets/javascripts/plugins/dropzone/dropzone.js",
    "lib/assets/javascripts/plugins/easypiechart/easypiechart.js",
    "lib/assets/javascripts/plugins/easypiechart/jquery.easypiechart.js",
    "lib/assets/javascripts/plugins/fancybox/blank.gif",
    "lib/assets/javascripts/plugins/fancybox/fancybox_loading.gif",
    "lib/assets/javascripts/plugins/fancybox/fancybox_loading@2x.gif",
    "lib/assets/javascripts/plugins/fancybox/fancybox_overlay.png",
    "lib/assets/javascripts/plugins/fancybox/fancybox_sprite.png",
    "lib/assets/javascripts/plugins/fancybox/fancybox_sprite@2x.png",
    "lib/assets/javascripts/plugins/fancybox/helpers/fancybox_buttons.png",
    "lib/assets/javascripts/plugins/fancybox/helpers/jquery.fancybox-buttons.css",
    "lib/assets/javascripts/plugins/fancybox/helpers/jquery.fancybox-buttons.js",
    "lib/assets/javascripts/plugins/fancybox/helpers/jquery.fancybox-media.js",
    "lib/assets/javascripts/plugins/fancybox/helpers/jquery.fancybox-thumbs.css",
    "lib/assets/javascripts/plugins/fancybox/helpers/jquery.fancybox-thumbs.js",
    "lib/assets/javascripts/plugins/fancybox/jquery.fancybox.css",
    "lib/assets/javascripts/plugins/fancybox/jquery.fancybox.js",
    "lib/assets/javascripts/plugins/fancybox/jquery.fancybox.pack.js",
    "lib/assets/javascripts/plugins/flot/curvedLines.js",
    "lib/assets/javascripts/plugins/flot/excanvas.min.js",
    "lib/assets/javascripts/plugins/flot/jquery.flot.js",
    "lib/assets/javascripts/plugins/flot/jquery.flot.pie.js",
    "lib/assets/javascripts/plugins/flot/jquery.flot.resize.js",
    "lib/assets/javascripts/plugins/flot/jquery.flot.spline.js",
    "lib/assets/javascripts/plugins/flot/jquery.flot.symbol.js",
    "lib/assets/javascripts/plugins/flot/jquery.flot.tooltip.min.js",
    "lib/assets/javascripts/plugins/fullcalendar/fullcalendar.min.js",
    "lib/assets/javascripts/plugins/gritter/images/gritter-light.png",
    "lib/assets/javascripts/plugins/gritter/images/gritter-long.png",
    "lib/assets/javascripts/plugins/gritter/images/gritter.png",
    "lib/assets/javascripts/plugins/gritter/images/ie-spacer.gif",
    "lib/assets/javascripts/plugins/gritter/jquery.gritter.css",
    "lib/assets/javascripts/plugins/gritter/jquery.gritter.min.js",
    "lib/assets/javascripts/plugins/iCheck/icheck.min.js",
    "lib/assets/javascripts/plugins/ionRangeSlider/ion.rangeSlider.min.js",
    "lib/assets/javascripts/plugins/jasny/jasny-bootstrap.min.js",
    "lib/assets/javascripts/plugins/jeditable/jquery.jeditable.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery-ui-i18n.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-af.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ar-DZ.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ar.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-az.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-be.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-bg.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-bs.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ca.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-cs.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-cy-GB.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-da.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-de.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-el.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-en-AU.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-en-GB.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-en-NZ.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-eo.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-es.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-et.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-eu.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-fa.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-fi.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-fo.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-fr-CA.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-fr-CH.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-fr.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-gl.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-he.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-hi.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-hr.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-hu.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-hy.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-id.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-is.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-it.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ja.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ka.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-kk.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-km.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ko.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ky.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-lb.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-lt.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-lv.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-mk.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ml.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ms.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-nb.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-nl-BE.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-nl.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-nn.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-no.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-pl.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-pt-BR.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-pt.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-rm.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ro.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ru.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-sk.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-sl.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-sq.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-sr-SR.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-sr.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-sv.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-ta.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-th.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-tj.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-tr.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-uk.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-vi.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-zh-CN.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-zh-HK.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/i18n/jquery.ui.datepicker-zh-TW.min.js",
    "lib/assets/javascripts/plugins/jquery-ui/images/animated-overlay.gif",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_flat_75_ffffff_40x100.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_glass_55_fbf9ee_1x400.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_glass_75_dadada_1x400.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_glass_75_e6e6e6_1x400.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_glass_95_fef1ec_1x400.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-icons_222222_256x240.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-icons_2e83ff_256x240.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-icons_454545_256x240.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-icons_888888_256x240.png",
    "lib/assets/javascripts/plugins/jquery-ui/images/ui-icons_cd0a0a_256x240.png",
    "lib/assets/javascripts/plugins/jquery-ui/jquery-ui.css",
    "lib/assets/javascripts/plugins/jquery-ui/jquery-ui.js",
    "lib/assets/javascripts/plugins/jquery-ui/jquery-ui.min.css",
    "lib/assets/javascripts/plugins/jquery-ui/jquery-ui.min.js",
    "lib/assets/javascripts/plugins/jsKnob/jquery.knob.js",
    "lib/assets/javascripts/plugins/justified-gallery/README.md",
    "lib/assets/javascripts/plugins/justified-gallery/jquery.justifiedgallery.css",
    "lib/assets/javascripts/plugins/justified-gallery/jquery.justifiedgallery.js",
    "lib/assets/javascripts/plugins/justified-gallery/jquery.justifiedgallery.min.css",
    "lib/assets/javascripts/plugins/justified-gallery/jquery.justifiedgallery.min.js",
    "lib/assets/javascripts/plugins/justified-gallery/loading.gif",
    "lib/assets/javascripts/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "lib/assets/javascripts/plugins/jvectormap/jquery-jvectormap-world-mill-en.js",
    "lib/assets/javascripts/plugins/metisMenu/jquery.metisMenu.js",
    "lib/assets/javascripts/plugins/morris/morris.js",
    "lib/assets/javascripts/plugins/morris/raphael-2.1.0.min.js",
    "lib/assets/javascripts/plugins/nouslider/jquery.nouislider.min.js",
    "lib/assets/javascripts/plugins/pace/pace.min.js",
    "lib/assets/javascripts/plugins/peity/jquery.peity.min.js",
    "lib/assets/javascripts/plugins/rickshaw/rickshaw.min.js",
    "lib/assets/javascripts/plugins/rickshaw/vendor/d3.v3.js",
    "lib/assets/javascripts/plugins/slimscroll/jquery.slimscroll.js",
    "lib/assets/javascripts/plugins/slimscroll/jquery.slimscroll.min.js",
    "lib/assets/javascripts/plugins/sparkline/jquery.sparkline.min.js",
    "lib/assets/javascripts/plugins/staps/jquery.steps.min.js",
    "lib/assets/javascripts/plugins/summernote/summernote.min.js",
    "lib/assets/javascripts/plugins/switchery/switchery.js",
    "lib/assets/javascripts/plugins/validate/jquery.validate.min.js",
    "lib/assets/javascripts/plugins/video/responsible-video.js",
    "lib/assets/javascripts/summernote.js",
    "lib/assets/javascripts/summernote.min.js",
    "lib/assets/javascripts/to-markdown.js",
    "lib/assets/stylesheets/.keep",
    "lib/assets/stylesheets/bootstrap-datetimepicker.css",
    "lib/assets/stylesheets/bootstrap-editable.css",
    "lib/assets/stylesheets/bootstrap-markdown.min.css",
    "lib/assets/stylesheets/framework/badgets_labels.sass",
    "lib/assets/stylesheets/framework/base.sass",
    "lib/assets/stylesheets/framework/buttons.sass",
    "lib/assets/stylesheets/framework/custom.sass",
    "lib/assets/stylesheets/framework/elements.sass",
    "lib/assets/stylesheets/framework/media.sass",
    "lib/assets/stylesheets/framework/mixins.sass",
    "lib/assets/stylesheets/framework/navigation.sass",
    "lib/assets/stylesheets/framework/pages.sass",
    "lib/assets/stylesheets/framework/sidebar.sass",
    "lib/assets/stylesheets/framework/skins.sass",
    "lib/assets/stylesheets/framework/style.sass",
    "lib/assets/stylesheets/framework/theme-config.sass",
    "lib/assets/stylesheets/framework/typography.sass",
    "lib/assets/stylesheets/framework/variables.sass",
    "lib/assets/stylesheets/jqueryui-editable.css",
    "lib/assets/stylesheets/plugins/chosen/chosen-sprite.png",
    "lib/assets/stylesheets/plugins/chosen/chosen-sprite@2x.png",
    "lib/assets/stylesheets/plugins/chosen/chosen.css",
    "lib/assets/stylesheets/plugins/dataTables/dataTables.bootstrap.css",
    "lib/assets/stylesheets/plugins/datapicker/datepicker3.css",
    "lib/assets/stylesheets/plugins/dropzone/basic.css",
    "lib/assets/stylesheets/plugins/dropzone/dropzone.css",
    "lib/assets/stylesheets/plugins/fullcalendar/fullcalendar.css",
    "lib/assets/stylesheets/plugins/fullcalendar/fullcalendar.print.css",
    "lib/assets/stylesheets/plugins/iCheck/custom.css",
    "lib/assets/stylesheets/plugins/iCheck/green.png",
    "lib/assets/stylesheets/plugins/iCheck/green@2x.png",
    "lib/assets/stylesheets/plugins/images/sort.png",
    "lib/assets/stylesheets/plugins/images/sort_asc.png",
    "lib/assets/stylesheets/plugins/images/sort_desc.png",
    "lib/assets/stylesheets/plugins/images/sprite-skin-flat.png",
    "lib/assets/stylesheets/plugins/images/sprite-skin-flat2.png",
    "lib/assets/stylesheets/plugins/images/sprite-skin-nice.png",
    "lib/assets/stylesheets/plugins/images/sprite-skin-simple.png",
    "lib/assets/stylesheets/plugins/images/spritemap.png",
    "lib/assets/stylesheets/plugins/images/spritemap@2x.png",
    "lib/assets/stylesheets/plugins/ionRangeSlider/ion.rangeSlider.css",
    "lib/assets/stylesheets/plugins/ionRangeSlider/ion.rangeSlider.skinFlat.css",
    "lib/assets/stylesheets/plugins/ionRangeSlider/ion.rangeSlider.skinNice.css",
    "lib/assets/stylesheets/plugins/ionRangeSlider/ion.rangeSlider.skinSimple.css",
    "lib/assets/stylesheets/plugins/jasny/jasny-bootstrap.min.css",
    "lib/assets/stylesheets/plugins/morris/morris-0.4.3.min.css",
    "lib/assets/stylesheets/plugins/nouslider/jquery.nouislider.css",
    "lib/assets/stylesheets/plugins/social-buttons/social-buttons.css",
    "lib/assets/stylesheets/plugins/steps/jquery.steps.css",
    "lib/assets/stylesheets/plugins/summernote/summernote-bs3.css",
    "lib/assets/stylesheets/plugins/summernote/summernote.css",
    "lib/assets/stylesheets/plugins/switchery/switchery.css",
    "lib/assets/stylesheets/summernote-bs2.css",
    "lib/assets/stylesheets/summernote-bs3.css",
    "lib/assets/stylesheets/summernote.css",
    "lib/quick-admin.rb",
    "lib/quick_admin/datagrid.rb",
    "lib/quick_admin/rails.rb",
    "quick-admin.gemspec",
    "spec/helpers/quick_admin_helper_spec.rb"
  ]
  s.homepage = "http://github.com/lazing/quick-admin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "easy to customize quick administrator backend framework"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 4.2.0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<haml-rails>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-rails>, [">= 0"])
      s.add_runtime_dependency(%q<meta-tags>, [">= 0"])
      s.add_runtime_dependency(%q<simple_form>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<datagrid>, [">= 0"])
      s.add_runtime_dependency(%q<responders>, ["~> 2.0"])
      s.add_runtime_dependency(%q<nprogress-rails>, [">= 0"])
      s.add_runtime_dependency(%q<sass-rails>, [">= 0"])
      s.add_runtime_dependency(%q<bootstrap-sass>, [">= 0"])
      s.add_runtime_dependency(%q<font-awesome-rails>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<rspec-activemodel-mocks>, [">= 0"])
      s.add_development_dependency(%q<spring>, [">= 0"])
      s.add_development_dependency(%q<spring-commands-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-haml>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 4.2.0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<haml-rails>, [">= 0"])
      s.add_dependency(%q<coffee-rails>, [">= 0"])
      s.add_dependency(%q<meta-tags>, [">= 0"])
      s.add_dependency(%q<simple_form>, ["~> 3.1.0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<datagrid>, [">= 0"])
      s.add_dependency(%q<responders>, ["~> 2.0"])
      s.add_dependency(%q<nprogress-rails>, [">= 0"])
      s.add_dependency(%q<sass-rails>, [">= 0"])
      s.add_dependency(%q<bootstrap-sass>, [">= 0"])
      s.add_dependency(%q<font-awesome-rails>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<rspec-activemodel-mocks>, [">= 0"])
      s.add_dependency(%q<spring>, [">= 0"])
      s.add_dependency(%q<spring-commands-rspec>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard-haml>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 4.2.0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<haml-rails>, [">= 0"])
    s.add_dependency(%q<coffee-rails>, [">= 0"])
    s.add_dependency(%q<meta-tags>, [">= 0"])
    s.add_dependency(%q<simple_form>, ["~> 3.1.0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<datagrid>, [">= 0"])
    s.add_dependency(%q<responders>, ["~> 2.0"])
    s.add_dependency(%q<nprogress-rails>, [">= 0"])
    s.add_dependency(%q<sass-rails>, [">= 0"])
    s.add_dependency(%q<bootstrap-sass>, [">= 0"])
    s.add_dependency(%q<font-awesome-rails>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<rspec-activemodel-mocks>, [">= 0"])
    s.add_dependency(%q<spring>, [">= 0"])
    s.add_dependency(%q<spring-commands-rspec>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard-haml>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

