# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quick-admin 4.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "quick-admin"
  s.version = "4.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ryan Wong"]
  s.date = "2015-04-09"
  s.description = "\n\n    * bootstrap 3\n    * fontawesome\n    * haml\n    * datagrid\n    * responders\n    * kaminari\n\n  "
  s.email = "lazing@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/quick-admin/base.coffee",
    "app/assets/stylesheets/quick-admin/base.scss",
    "app/controllers/quick_admin/base_controller.rb",
    "app/helpers/quick_admin_helper.rb",
    "app/views/datagrid/_range_filter.html.haml",
    "app/views/kaminari/_first_page.html.haml",
    "app/views/kaminari/_gap.html.haml",
    "app/views/kaminari/_last_page.html.haml",
    "app/views/kaminari/_next_page.html.haml",
    "app/views/kaminari/_page.html.haml",
    "app/views/kaminari/_paginator.html.haml",
    "app/views/kaminari/_prev_page.html.haml",
    "app/views/layouts/_menu.html.haml",
    "app/views/layouts/application.html.haml",
    "app/views/layouts/quick_admin/base.html.haml",
    "app/views/quick_admin/_action_show.html.haml",
    "app/views/quick_admin/_item.html.haml",
    "app/views/quick_admin/base/_scopes.html.haml",
    "app/views/quick_admin/base/destroy.js.coffee",
    "app/views/quick_admin/base/edit.html.haml",
    "app/views/quick_admin/base/index.html.haml",
    "app/views/quick_admin/base/new.html.haml",
    "app/views/quick_admin/base/show.html.haml",
    "app/views/quick_grid/_form.html.haml",
    "app/views/quick_grid/_head.html.haml",
    "app/views/quick_grid/_order_for.html.haml",
    "app/views/quick_grid/_row.html.haml",
    "app/views/quick_grid/_table.html.haml",
    "lib/quick-admin.rb",
    "lib/quick_admin/datagrid.rb",
    "lib/quick_admin/rails.rb",
    "quick-admin.gemspec",
    "spec/helpers/quick_admin_helper_spec.rb",
    "vendor/assets/javascripts/jquery.cascadingdropdown.js"
  ]
  s.homepage = "http://github.com/lazing/quick-admin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "easy to customize quick administrator backend framework"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 4.2"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<haml-rails>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-rails>, [">= 0"])
      s.add_runtime_dependency(%q<meta-tags>, [">= 0"])
      s.add_runtime_dependency(%q<simple_form>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<datagrid>, [">= 0"])
      s.add_runtime_dependency(%q<responders>, ["~> 2.0"])
      s.add_runtime_dependency(%q<nprogress-rails>, [">= 0"])
      s.add_runtime_dependency(%q<sass-rails>, [">= 0"])
      s.add_runtime_dependency(%q<font-awesome-rails>, [">= 0"])
      s.add_runtime_dependency(%q<semantic-ui-sass>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-ui-rails>, [">= 0"])
      s.add_runtime_dependency(%q<turbolinks>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-turbolinks>, [">= 0"])
      s.add_runtime_dependency(%q<pickadate-rails>, [">= 0"])
      s.add_runtime_dependency(%q<sprockets-rails>, [">= 0"])
      s.add_development_dependency(%q<pry-rails>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<rspec-activemodel-mocks>, [">= 0"])
      s.add_development_dependency(%q<spring>, [">= 0"])
      s.add_development_dependency(%q<spring-commands-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-haml>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 4.2"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<haml-rails>, [">= 0"])
      s.add_dependency(%q<coffee-rails>, [">= 0"])
      s.add_dependency(%q<meta-tags>, [">= 0"])
      s.add_dependency(%q<simple_form>, ["~> 3.1.0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<datagrid>, [">= 0"])
      s.add_dependency(%q<responders>, ["~> 2.0"])
      s.add_dependency(%q<nprogress-rails>, [">= 0"])
      s.add_dependency(%q<sass-rails>, [">= 0"])
      s.add_dependency(%q<font-awesome-rails>, [">= 0"])
      s.add_dependency(%q<semantic-ui-sass>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<jquery-ui-rails>, [">= 0"])
      s.add_dependency(%q<turbolinks>, [">= 0"])
      s.add_dependency(%q<jquery-turbolinks>, [">= 0"])
      s.add_dependency(%q<pickadate-rails>, [">= 0"])
      s.add_dependency(%q<sprockets-rails>, [">= 0"])
      s.add_dependency(%q<pry-rails>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<rspec-activemodel-mocks>, [">= 0"])
      s.add_dependency(%q<spring>, [">= 0"])
      s.add_dependency(%q<spring-commands-rspec>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard-haml>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 4.2"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<haml-rails>, [">= 0"])
    s.add_dependency(%q<coffee-rails>, [">= 0"])
    s.add_dependency(%q<meta-tags>, [">= 0"])
    s.add_dependency(%q<simple_form>, ["~> 3.1.0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<datagrid>, [">= 0"])
    s.add_dependency(%q<responders>, ["~> 2.0"])
    s.add_dependency(%q<nprogress-rails>, [">= 0"])
    s.add_dependency(%q<sass-rails>, [">= 0"])
    s.add_dependency(%q<font-awesome-rails>, [">= 0"])
    s.add_dependency(%q<semantic-ui-sass>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<jquery-ui-rails>, [">= 0"])
    s.add_dependency(%q<turbolinks>, [">= 0"])
    s.add_dependency(%q<jquery-turbolinks>, [">= 0"])
    s.add_dependency(%q<pickadate-rails>, [">= 0"])
    s.add_dependency(%q<sprockets-rails>, [">= 0"])
    s.add_dependency(%q<pry-rails>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<rspec-activemodel-mocks>, [">= 0"])
    s.add_dependency(%q<spring>, [">= 0"])
    s.add_dependency(%q<spring-commands-rspec>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard-haml>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

